### PR TITLE
Vc707 nopcie switchable

### PR DESCRIPTION
**Pull request by mcd500**
It will enable to build for vc707 with and without PCIe-HMC board selectable as discussed in #116.
This pull request require to merge after the pull request of "fpga-shells" submodule. https://github.com/sifive/fpga-shells/pull/64

### CODE REVIEW

**Comment by erikdanie** [comment]
Thanks for doing this! looks pretty good at first glance, I'm gonna review it deeper sometime in the next few days when I get a chance

**Comment by mcd500** [comment]
You are most welcome!

**Comment by mcd500** [comment]
gentle reminder ping?

**Comment by mcd500** [comment]
I pushed it in the PR after rebasing to master in `fpga-shells`. As the discussion at https://github.com/sifive/fpga-shells/pull/64, it has some build errors. It might be good to move the discussion here instead of submodule `fgpa-shells` since the changes seems to be require in freedom.git.

**Comment by erikdanie** [comment]
Now just make this fpga-shells point to https://github.com/sifive/fpga-shells/tree/revert-43-fpga-spi_speedup, then make a few builds to confirm it works, and we can finally merge this

**Comment by mcd500** [comment]
After I changed the fpga-shells point to https://github.com/sifive/fpga-shells/tree/revert-43-fpga-spi_speedup, I realized one more change was required. Do you mind merging https://github.com/sifive/fpga-shells/pull/80 to make this PR to be buildable?

**Comment by mcd500** [comment]
Also I would like to make PR which uses the https://github.com/sifive/fpga-shells/pull/79 for tracking master branch of fpga-shells in freedom.git on vc707. Which branch in freedom.git I should choose for this PR?

**Comment by erikdanie** [comment]
So I think you just need to make this PR point to the correct fpga-shells and test out the build and we are ready to go

**Comment by mcd500** [comment]
@erikdanie  I changed it to point fpga-shells to the merged https://github.com/sifive/fpga-shells/pull/80. Appreciate for merging.

**Comment by erikdanie** [comment]
Great, thanks again for the help! Have you confirmed that this build works on your board? If so, I will merge. Otherwise I will try for myself sometime next week

**Comment by mcd500** [comment]
Yes, I confirmed the builds for both with and without PCIe module works fine. thanks

**Comment by mcd500** [comment]
Do you mind merging this today together with this PR? https://github.com/sifive/freedom/pull/133

**Comment by erikdanie** [comment]
Ok, thanks!

**Pull request merged**
